version: 1.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu

build_script:
  - dotnet build DistributedLock.sln -c Release
  
test_script:
  - dotnet test DistributedLock.sln -c Release -f netcoreapp3.1 --no-build --filter TestCategory=CI

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2019"
    test_script:
      - dotnet test DistributedLock.sln -c Release --no-build --filter "TestCategory=CI|TestCategory=CIWindows"